import { useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import toast from 'react-hot-toast'
import { Download, FileText, RotateCw, ShieldX } from 'lucide-react'
import {
  Badge,
  Button,
  Card,
  CardBody,
  ConfirmDialog,
  DataTable,
  Drawer,
  EmptyState,
  FilterBar,
  KeyValue,
  KeyValueList,
  PageHeader,
  Skeleton,
  StatusBadge,
  Timeline,
  type Column,
  type TimelineItem,
} from '@/ui'
import {
  documentTemplatesCollection,
  generatedDocumentsCollection,
  useCollection,
} from '@/mocks'
import type { GeneratedDocument } from '@/mocks'
import { formatDateTime, humanize } from '@/lib/format'
import { personName, useActingUser, useScreenState, userName, WorkGroupTabs } from './shared'
import { writeAudit } from './engine'

const SIGNATURE_LABEL: Record<GeneratedDocument['signatureStatus'], string> = {
  not_required: 'Not required',
  awaiting: 'Awaiting',
  signed: 'Signed',
  declined: 'Declined',
}

export default function Documents() {
  const [params, setParams] = useSearchParams()
  const { loading, error, retry } = useScreenState(params.get('demo') === 'error')
  const acting = useActingUser()

  const documents = useCollection(generatedDocumentsCollection)
  const templates = useCollection(documentTemplatesCollection)

  const [voidTarget, setVoidTarget] = useState<GeneratedDocument | null>(null)

  const set = (key: string, value: string | undefined) => {
    const next = new URLSearchParams(params)
    if (!value) next.delete(key)
    else next.set(key, value)
    setParams(next, { replace: true })
  }

  const q = params.get('q') ?? ''
  const type = params.get('type') ?? ''
  const signature = params.get('signature') ?? ''
  const drawerId = params.get('drawer')
  const open = documents.find((d) => d.id === drawerId)

  const types = useMemo(() => [...new Set(documents.map((d) => d.type))].sort(), [documents])

  const filtered = useMemo(() => {
    const needle = q.trim().toLowerCase()
    return documents
      .filter((d) => !needle || d.ref.toLowerCase().includes(needle) || personName(d.personId).toLowerCase().includes(needle))
      .filter((d) => !type || d.type === type)
      .filter((d) => !signature || d.signatureStatus === signature)
      .sort((a, b) => Date.parse(b.generatedAt) - Date.parse(a.generatedAt))
      .slice(0, 200)
  }, [documents, q, type, signature])

  const columns: Array<Column<GeneratedDocument>> = [
    { key: 'ref', header: 'Document', width: 170, accessor: (d) => d.ref, sortable: true, pinned: true },
    { key: 'type', header: 'Type', width: 140, accessor: (d) => humanize(d.type), sortable: true },
    { key: 'person', header: 'Person', width: 180, accessor: (d) => personName(d.personId), sortable: true },
    { key: 'related', header: 'Related record', width: 170, accessor: (d) => `${d.relatedEntityType}`, sortable: true },
    {
      key: 'template',
      header: 'Template',
      width: 210,
      accessor: (d) => `${templates.find((t) => t.id === d.templateId)?.name ?? '—'} v${d.templateVersion}`,
      sortable: true,
    },
    { key: 'by', header: 'Generated by', width: 160, accessor: (d) => userName(d.generatedByUserId), sortable: true },
    {
      key: 'at',
      header: 'Generated',
      width: 170,
      accessor: (d) => formatDateTime(d.generatedAt),
      sortValue: (d) => d.generatedAt,
      sortable: true,
    },
    {
      key: 'signature',
      header: 'Signature',
      width: 130,
      cell: (d) => <StatusBadge status={d.signatureStatus} label={SIGNATURE_LABEL[d.signatureStatus]} size="sm" />,
      sortValue: (d) => d.signatureStatus,
      sortable: true,
    },
    {
      key: 'signedAt',
      header: 'Signed',
      width: 160,
      accessor: (d) => (d.signedAt ? formatDateTime(d.signedAt) : '—'),
      sortValue: (d) => d.signedAt ?? '',
      sortable: true,
    },
    {
      key: 'status',
      header: 'Status',
      width: 110,
      cell: (d) => (d.voidedAt ? <Badge tone="danger" size="sm">Voided</Badge> : <Badge tone="success" size="sm">Live</Badge>),
      sortValue: (d) => (d.voidedAt ? 1 : 0),
      sortable: true,
    },
  ]

  const signatureTrail = (doc: GeneratedDocument): TimelineItem[] => {
    const items: TimelineItem[] = [
      {
        id: 'generated',
        title: 'Generated',
        description: `${userName(doc.generatedByUserId)} generated ${doc.ref} from ${templates.find((t) => t.id === doc.templateId)?.name ?? 'a template'} v${doc.templateVersion}. An audit event was written.`,
        timestamp: doc.generatedAt,
        tone: 'info',
      },
    ]
    if (doc.signatureStatus !== 'not_required') {
      items.push({
        id: 'sent',
        title: 'Sent for signature',
        description: `${doc.signatories.length} signatory block${doc.signatories.length === 1 ? '' : 's'}.`,
        timestamp: doc.generatedAt,
        tone: 'neutral',
      })
    }
    doc.signatories.forEach((signatory, index) => {
      items.push({
        id: `sig-${index}`,
        title: signatory.signedAt ? `Signed by ${personName(signatory.personId)}` : `Awaiting ${personName(signatory.personId)}`,
        description: signatory.signedAt
          ? 'Signature captured with actor, timestamp and document hash.'
          : 'No signature captured yet.',
        timestamp: signatory.signedAt ?? doc.generatedAt,
        tone: signatory.signedAt ? 'success' : 'warning',
      })
    })
    if (doc.voidedAt) {
      items.push({ id: 'void', title: 'Voided', description: 'The document stays visible. Nothing is hard-deleted.', timestamp: doc.voidedAt, tone: 'danger' })
    }
    return items
  }

  return (
    <div className="px-8 py-6">
      <PageHeader
        title="Documents"
        description="Every generated document, the template version it came from, and its signature trail."
        breadcrumbs={[{ label: 'Work', to: '/work' }, { label: 'Documents' }]}
      />

      <WorkGroupTabs group="documents" active="documents" />

      <FilterBar
        className="mt-6"
        search={q}
        onSearchChange={(v) => set('q', v)}
        searchPlaceholder="Search by ref or person"
        values={{ type, signature }}
        onFilterChange={set}
        onClearAll={() => setParams(new URLSearchParams(), { replace: true })}
        filters={[
          { key: 'type', label: 'Type', options: types.map((t) => ({ value: t, label: humanize(t) })) },
          {
            key: 'signature',
            label: 'Signature',
            options: (Object.keys(SIGNATURE_LABEL) as Array<GeneratedDocument['signatureStatus']>).map((s) => ({
              value: s,
              label: SIGNATURE_LABEL[s],
            })),
          },
        ]}
      />

      {loading ? (
        <Card className="mt-4">
          <CardBody className="space-y-2">
            {Array.from({ length: 8 }).map((_, i) => (
              <Skeleton key={i} height={40} rounded="lg" />
            ))}
          </CardBody>
        </Card>
      ) : error ? (
        <Card className="mt-4">
          <CardBody>
            <EmptyState variant="error" title="Could not load documents" message={error} action={<Button onClick={retry}>Retry</Button>} />
          </CardBody>
        </Card>
      ) : (
        <Card className="mt-4">
          <CardBody padding="none">
            <DataTable
              data={filtered}
              columns={columns}
              rowKey={(d) => d.id as string}
              caption="Generated documents with template version and signature status"
              density="compact"
              minWidth={1600}
              activeRowKey={drawerId ?? undefined}
              onRowClick={(d) => set('drawer', d.id as string)}
              emptyTitle="No documents match these filters."
              emptyMessage="Clear the filters to see everything that has been generated."
              emptyAction={
                <Button variant="secondary" onClick={() => setParams(new URLSearchParams(), { replace: true })}>
                  Clear filters
                </Button>
              }
            />
          </CardBody>
        </Card>
      )}

      <Drawer
        open={Boolean(open)}
        onClose={() => set('drawer', undefined)}
        title={open?.ref ?? 'Document'}
        description={open ? `${humanize(open.type)} · ${personName(open.personId)}` : undefined}
        size="lg"
        footer={
          open && (
            <>
              <Button variant="ghost" leftIcon={<Download size={16} />} onClick={() => toast('Not built in this prototype — this would download the PDF.')}>
                Download
              </Button>
              {open.signatureStatus === 'awaiting' && (
                <Button
                  variant="secondary"
                  leftIcon={<RotateCw size={16} />}
                  onClick={() => toast('Not built in this prototype — this would resend the signature request.')}
                >
                  Resend for signature
                </Button>
              )}
              {!open.voidedAt && (
                <Button variant="danger" leftIcon={<ShieldX size={16} />} onClick={() => setVoidTarget(open)}>
                  Void
                </Button>
              )}
            </>
          )
        }
      >
        {open && (
          <div className="space-y-5">
            <KeyValueList columns={2}>
              <KeyValue label="Template">{`${templates.find((t) => t.id === open.templateId)?.name ?? '—'} v${open.templateVersion}`}</KeyValue>
              <KeyValue label="Generated by">{userName(open.generatedByUserId)}</KeyValue>
              <KeyValue label="Generated at">{formatDateTime(open.generatedAt)}</KeyValue>
              <KeyValue label="Signature">{SIGNATURE_LABEL[open.signatureStatus]}</KeyValue>
              <KeyValue label="File">{open.fileUrl}</KeyValue>
              <KeyValue label="Status">{open.voidedAt ? 'Voided' : 'Live'}</KeyValue>
            </KeyValueList>
            <div>
              <p className="text-label-11 text-text-label">Signature audit trail</p>
              <div className="mt-2">
                <Timeline items={signatureTrail(open)} timeFormat="absolute" />
              </div>
            </div>
          </div>
        )}
      </Drawer>

      <ConfirmDialog
        open={voidTarget !== null}
        onClose={() => setVoidTarget(null)}
        title="Void this document"
        message={
          voidTarget
            ? `${voidTarget.ref} will be marked void and stay visible in this list with its full history. It is not deleted, and any signature already captured is preserved.`
            : ''
        }
        confirmLabel="Void document"
        destructive
        icon={FileText}
        onConfirm={() => {
          if (!voidTarget) return
          const now = new Date().toISOString()
          generatedDocumentsCollection.update(voidTarget.id, { voidedAt: now, updatedAt: now, updatedBy: acting })
          writeAudit({
            actorUserId: acting,
            action: 'document.void',
            entityType: 'GeneratedDocument',
            entityId: voidTarget.id as string,
            entityRef: voidTarget.ref,
            field: 'voidedAt',
            before: null,
            after: now,
          })
          toast.success(`${voidTarget.ref} voided. The row stays visible.`)
          setVoidTarget(null)
        }}
      />
    </div>
  )
}
